# Generated by Django 5.1.1 on 2024-11-28 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_category_remove_book_author_person_delete_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="person",
            name="cat",
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("publication_date", models.DateField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FIC", "Fiction"),
                            ("NON", "Non-Fiction"),
                            ("SCI", "Sciencee Fiction"),
                            ("FAN", "Fantasy"),
                            ("MYS", "Mystery"),
                        ],
                        default="FIC",
                        max_length=3,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="app.author",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
